/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import fonts.Fonts;
import javax.swing.JPanel;
import view.FEmilio.*;
/**
 *
 * @author JAIMEUNL
 */
public class Menu_Bidi_A_O extends javax.swing.JPanel {

    /**
     * Creates new form Menu_Figuras
     */
    public Menu_Bidi_A_O() {
        initComponents();
        btn_Regresar.setVisible(true);
    }
    
    Fonts tipoFuente = new Fonts();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_Regresar = new javax.swing.JButton();
        cbxfigurasA = new javax.swing.JComboBox<>();
        btnabrircal = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(610, 240));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(tipoFuente.fuente(tipoFuente.FSEX, 1, 20));
        jLabel3.setText("Figuras Bidimensionales");

        btn_Regresar.setText("Regresar");
        btn_Regresar.setFont(tipoFuente.fuente(tipoFuente.FSEX, 1, 15));
        btn_Regresar.setVisible(false);
        btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresarActionPerformed(evt);
            }
        });

        cbxfigurasA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arco circular", "Círculo", "Círculo concéntrico", "Corona circular", "Corazón", "Decágono", "Dodecágono", "Elipse", "Eneágono", "Estrella de 5 puntas", "Estrella de 6 puntas", "Heptágono", "Hexágono", "Octágono", "Octágono regular con apotema" }));
        cbxfigurasA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxfigurasAActionPerformed(evt);
            }
        });

        btnabrircal.setText("Abrir Calculadora");
        btnabrircal.setFont(tipoFuente.fuente(tipoFuente.FSEX, 1, 30));
        btnabrircal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabrircalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(cbxfigurasA, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnabrircal, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(btn_Regresar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxfigurasA, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnabrircal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresarActionPerformed
        // TODO add your handling code here:
        Menu_Bidimensionales menu_Bidimensionales = new Menu_Bidimensionales();
        Main_Frame.showPanel(this, menu_Bidimensionales);
    }//GEN-LAST:event_btn_RegresarActionPerformed

    private void btnabrircalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabrircalActionPerformed
        // TODO add your handling code here:
         String figura = cbxfigurasA.getSelectedItem().toString();
        seleccion(figura);
    }//GEN-LAST:event_btnabrircalActionPerformed
public void regresar(JPanel panel){
        Main_Frame.showPanel(this, panel);
    }
    
    public void seleccion(String figura) {
        switch (figura) {
            case "Arco circular":
                area_Arco_circular AC = new area_Arco_circular();
                Main_Frame.showPanel(this, AC);
                break;
            case "Círculo":
                area_Circulo C = new area_Circulo();
                Main_Frame.showPanel(this, C);
                break;
            case "Círculo concéntrico":
                area_Circulo_Concentrico CC = new area_Circulo_Concentrico();
                Main_Frame.showPanel(this, CC);
                break;
            case "Corona circular":
                area_Corona_circular CCir = new area_Corona_circular();
                Main_Frame.showPanel(this, CCir);
                break;
            case "Corazón":
                area_Corazon Co = new area_Corazon();
                Main_Frame.showPanel(this, Co);
                break;
            case "Dodecágono":
                area_Dodecagono D = new area_Dodecagono();
                Main_Frame.showPanel(this, D);
                break;
            case "Elipse":
                area_Elipse E = new area_Elipse();
                Main_Frame.showPanel(this, E);
                break;
            case "Eneágono":
                area_Eneágono En = new area_Eneágono();
                Main_Frame.showPanel(this, En);
                break;
            case "Estrella de 5 puntas":
                area_Estrella_5_Puntas E5 = new area_Estrella_5_Puntas();
                Main_Frame.showPanel(this, E5);
                break;
            case "Estrella de 6 puntas":
                area_Estrella_6_Puntas E6 = new area_Estrella_6_Puntas();
                Main_Frame.showPanel(this, E6);
                break;
            case "Heptágono":
                area_heptagono H = new area_heptagono();
                Main_Frame.showPanel(this, H);
                break;
            case "Hexágono":
                area_Hexagono Hex = new area_Hexagono();
                Main_Frame.showPanel(this, Hex);
                break;
            case "Octágono":
                area_Octagono O = new area_Octagono();
                Main_Frame.showPanel(this, O);
                break;
            case "Octágono regular con apotema":
                area_Octagono_regular_AP ORAp = new area_Octagono_regular_AP();
                Main_Frame.showPanel(this, ORAp);
                break;
            case "Decágono":
                area_Decagono De = new area_Decagono();
                Main_Frame.showPanel(this, De);
                break;
        }
    }
    
    
    private void cbxfigurasAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxfigurasAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxfigurasAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_Regresar;
    private javax.swing.JButton btnabrircal;
    private javax.swing.JComboBox<String> cbxfigurasA;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
