/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import fonts.Fonts;
import javax.swing.JPanel;
import view.FAlex.areaParalelogramo;
import view.FAlex.areaPentagono;
import view.FAlex.areaRombo;
import view.FAlex.areaRomboide;
import view.FAlex.areaSectorcircular;
import view.FAlex.areaSegmentocircular;
import view.FAlex.areaSegmentoeliptico;
import view.FAlex.areaSemicirculo;
import view.FAlex.areaTrapeciocircular;
import view.FAlex.areaTrapecioisoceles;
import view.FAlex.areaTriangulo;
import view.FAlex.areaTrianguloequilatero;
import view.FAlex.areaTrianguloescaleno;
import view.FAlex.areaTriqueta;

/**
 *
 * @author JAIMEUNL
 */
public class Menu_Bidi_A_O extends javax.swing.JPanel {

    /**
     * Creates new form Menu_Figuras
     */
    public Menu_Bidi_A_O() {
        initComponents();
        btn_Regresar.setVisible(true);
    }
    
    Fonts tipoFuente = new Fonts();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        btnabrircalc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_Regresar = new javax.swing.JButton();
        cbxfigurasA = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(610, 240));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(610, 240));

        btnabrircalc.setText("Abrir Calculadora");
        btnabrircalc.setFont(tipoFuente.fuente(tipoFuente.FSEX, 1, 30));
        btnabrircalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabrircalcActionPerformed(evt);
            }
        });

        jLabel3.setFont(tipoFuente.fuente(tipoFuente.FSEX, 1, 20));
        jLabel3.setText("Figuras Bidimensionales");

        btn_Regresar.setText("Regresar");
        btn_Regresar.setFont(tipoFuente.fuente(tipoFuente.FSEX, 1, 15));
        btn_Regresar.setVisible(false);
        btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresarActionPerformed(evt);
            }
        });

        cbxfigurasA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arco circular", "Círculo", "Círculo concéntrico", "Corona circular", "Corazón", "Decágono", "Dodecágono", "Elipse", "Eneágono", "Estrella de 5 puntas", "Estrella de 6 puntas", "Heptágono", "Hexágono", "Octágono", "Octágono regular con apotema" }));
        cbxfigurasA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxfigurasAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(cbxfigurasA, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnabrircalc, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(btn_Regresar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnabrircalc, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxfigurasA, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnabrircalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabrircalcActionPerformed
        // TODO add your handling code here:
        seleccion(cbxfigurasA.getSelectedItem().toString());
    }//GEN-LAST:event_btnabrircalcActionPerformed
public void regresar(JPanel panel){
        Main_Frame.showPanel(this, panel);
    }
    
    public void seleccion(String figura){
        switch (figura){
            case "Paralelogramo":
                areaParalelogramo paralelogramo = new areaParalelogramo();
                Main_Frame.showPanel(bg, paralelogramo);
            case "Pentagono":
                areaPentagono pentagono = new areaPentagono();
                Main_Frame.showPanel(bg, pentagono);
            case "Rombo":
                areaRombo rombo = new areaRombo();
                Main_Frame.showPanel(bg, rombo);
            case "Romboide":
                areaRomboide romboide= new areaRomboide();
                Main_Frame.showPanel(bg, romboide);
            case "Sector circular":
                areaSectorcircular sectorcircular = new areaSectorcircular();
                Main_Frame.showPanel(bg, sectorcircular);
            case "Segmento circular":
                areaSegmentocircular segmentociecular = new areaSegmentocircular();
                Main_Frame.showPanel(bg, segmentociecular);
            case "Segmento elíptico":
                areaSegmentoeliptico segmentoeliptico = new areaSegmentoeliptico();
                Main_Frame.showPanel(bg, segmentoeliptico);
            case "Semicírculo":
                areaSemicirculo semicirculo = new areaSemicirculo();
                Main_Frame.showPanel(bg, semicirculo);
            case "Trapecio circular":
                areaTrapeciocircular trapeciocircular = new areaTrapeciocircular();
                Main_Frame.showPanel(bg, trapeciocircular);
            case "Trapecio isósceles":
                areaTrapecioisoceles trapeciosisoceles = new areaTrapecioisoceles();
                Main_Frame.showPanel(bg, trapeciosisoceles);
            case "Triángulo":
                areaTriangulo triangulo = new areaTriangulo();
                Main_Frame.showPanel(bg, triangulo);
            case "Triángulo equilátero":
                areaTrianguloequilatero trianguloequilatero = new areaTrianguloequilatero();
                Main_Frame.showPanel(bg, trianguloequilatero);
            case "Triángulo escaleno":
                areaTrianguloescaleno trianguloescaleno = new areaTrianguloescaleno();
                Main_Frame.showPanel(bg, trianguloescaleno);
            case "Triqueta":
                areaTriqueta triqueta = new areaTriqueta();
                Main_Frame.showPanel(bg, triqueta);
        }
                
    }
    private void btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresarActionPerformed
        // TODO add your handling code here:
        Menu_Bidimensionales menu_Bidimensionales = new Menu_Bidimensionales();
        Main_Frame.showPanel(bg, menu_Bidimensionales);
    }//GEN-LAST:event_btn_RegresarActionPerformed

    private void cbxfigurasAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxfigurasAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxfigurasAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_Regresar;
    private javax.swing.JButton btnabrircalc;
    private javax.swing.JComboBox<String> cbxfigurasA;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
